### ISSUE TITLE
"output file has already been set"  exception

### ISSUE THREAD

**Issue by jianzi0307** [dooboolab/flutter_sound#125]
flutter doctor
-------------
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.3-pre.56, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
[✓] VS Code (version 1.37.1)
[✓] Connected device (2 available)

• No issues found!
```

flutter_sound version
---------------------
```
flutter_sound: ^1.4.2
```

exception
---------------
```
D/FlutterSoundPlugin(16895): startRecorder
E/MediaRecorder(16895): output file has already been set
E/FlutterSoundPlugin(16895): Exception:
E/FlutterSoundPlugin(16895): java.lang.IllegalStateException
E/FlutterSoundPlugin(16895): 	at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin(16895): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:859)
E/FlutterSoundPlugin(16895): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:164)
E/FlutterSoundPlugin(16895): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:67)
E/FlutterSoundPlugin(16895): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(lambda)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/FlutterSoundPlugin(16895): 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by michalyashpe** [comment]
I experience the same issue

**Comment by hyochan** [comment]
Does this also happen in `1.4.4`? I've just tried myself in the `example` and can't reproduce this.

**Comment by cs118651** [comment]
same issue on Android HUAWEI HONOR 9X

**Comment by cs118651** [comment]
> same issue on Android HUAWEI HONOR 9X

I changed version from v1.4.5 to v1.4.4 and the issue is disappear

**Comment by sayhicoelho** [comment]
Same issue here

**Comment by hyochan** [comment]
What about in our recent version `2.0.3`? We've made some fixes related to this.

**Comment by Larpoux** [comment]
Please, feel free to re-open this issue if you thin it has not been fixed by recent versions.
