### ISSUE TITLE
Attempt to call getDuration in wrong state

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#204]
### Version of flutter_sound
Development branch on a private fork issued from MasterBranch flutter_sound 

### Platforms you faced the error (IOS or Android or both?)
Android API 24

### Actual behavior
Crash

### Tested environment (Emulator? Real Device?)
Emulator SDK API 24

### Steps to reproduce the behavior
Cannot reproduce.

-------------------------------------------------
```
D/FlutterSoundPlugin: Plays completed.
E/MediaPlayer: Attempt to call getDuration in wrong state: mPlayer=0x0, mCurrentState=1
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: Timer-1
    Process: com.dooboolab.fluttersoundexample, PID: 3514
    java.lang.IllegalStateException
        at android.media.MediaPlayer.getCurrentPosition(Native Method)
        at com.dooboolab.fluttersound.FlutterSoundPlugin$3.run(FlutterSoundPlugin.java:452)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Disconnected from the target VM, address: 'localhost:8834', transport: 'socket'
```

**Comment by Larpoux** [comment]
Today I got again this crash : 
```I/flutter: stopRecorder: recorder stopped.
D/FlutterSoundPlugin: mediaPlayer prepared and start
I/flutter: startPlayer result: /data/user/0/com.dooboolab.fluttersoundexample/cache/sound.aac
    startPlayer: /data/user/0/com.dooboolab.fluttersoundexample/cache/sound.aac
D/FlutterSoundPlugin: Plays completed.
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative: Attempt to call getDuration in wrong state: mPlayer=0x0, mCurrentState=1
    error (-38, 0)
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer: mediaplayer went away with unhandled events
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: Timer-3
    Process: com.dooboolab.fluttersoundexample, PID: 7876
    java.lang.IllegalStateException
        at android.media.MediaPlayer.getCurrentPosition(Native Method)
        at com.dooboolab.fluttersound.FlutterSoundPlugin$3.run(FlutterSoundPlugin.java:453)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
I/Process: Sending signal. PID: 7876 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
```

**Comment by Larpoux** [comment]
I forgot to mention that those two crashes was with flutter_sound example.

I will work on this bug later, when I will port my own app to Android : actually I am focused on iOS.

**Comment by Larpoux** [comment]
I am not having this crash since January.
The code is now protected by a try/catch.

I will re-open this bug if it will occurs again.
