### ISSUE TITLE
when i record  audio ,ofen have the exceptioon  "output file has already been set", how to solve

### ISSUE THREAD

**Issue by LxxHub** [dooboolab/flutter_sound#22]

**Comment by hyochan** [comment]
Please provide issue template to help you out.

**Comment by namnh06** [comment]
I got the same, this is my debug:
```
E/FlutterSoundPlugin( 7626): Exception:
E/FlutterSoundPlugin( 7626): java.lang.IllegalStateException
E/FlutterSoundPlugin( 7626): 	at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin( 7626): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:961)
E/FlutterSoundPlugin( 7626): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:164)
E/FlutterSoundPlugin( 7626): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:67)
E/FlutterSoundPlugin( 7626): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin( 7626): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/FlutterSoundPlugin( 7626): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin( 7626): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterSoundPlugin( 7626): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterSoundPlugin( 7626): 	at java.lang.Thread.run(Thread.java:764)
```
