### ISSUE TITLE
Just installed application and press 'record' button - throws exceptions. 

### ISSUE THREAD

**Issue by kmusham** [dooboolab/flutter_sound#220]
flutter_sound: ^2.0.3

    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

2020-02-14 14:50:57.759 27056-27321/? E/FlutterSoundPlugin: Exception: 
    java.io.FileNotFoundException: sound.aac: open failed: EROFS (Read-only file system)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
        at android.media.MediaRecorder.prepare(MediaRecorder.java:1046)
        at b.c.a.m.a(:3)
        at b.c.a.c.run(Unknown Source:8)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
        at android.media.MediaRecorder.prepare(MediaRecorder.java:1046) 
        at b.c.a.m.a(:3) 
        at b.c.a.c.run(Unknown Source:8) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by hyochan** [comment]
Have you tried our example app? I've note experienced this yet.

**Comment by DreamsInCS** [comment]
> Have you tried our example app? I've note experienced this yet.

Might I ask where this example app can be found?

**Comment by Larpoux** [comment]
Probably the caller try to write its record in an area forbidden by Android.
Correct directories can found with Flutter plugin `path_provider`.
I suggest to close this issue with is not on the flutter_sound side.

**Comment by hyochan** [comment]
@Larpoux Why wouldn't you get my invitation and we can maintain this together? Since I believe you are so much matured to understand what is going on in our repo. Then you can close it if you make a decision or you can also request help if you think someone should look into it.

**Comment by Larpoux** [comment]
Yes, Hyo.
I am very proud that you have confidence on me.
The only problem is that I would not like to be, one day, the main flutter_sound maintener.
I would do a poor job, because flutter_sound is not my main project.
We definitely need you as the main flutter_sound maintener.

**Comment by Larpoux** [comment]
Please, feel free to re-open this issue if you think that your problem is not solved by recent version of flutter-sound
