### ISSUE TITLE
[FLAUTO] Bad notification for startForeground

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#237]
### Version of flutter_sound
Flauto

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Example should play the Remote Example File

### Actual behavior
Fatal Exception

### Tested environment (Emulator? Real Device?)
Real Android MI Max 3

### Steps to reproduce the behavior
- Start the example
- Select Media = "Remote Example File"
- Play

@salvatore373 : your Example App seems to run OK on Android.
But with my own App I have the following Exception : 
```
I/flutter: startPlayer result: https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3
I/flutter: startPlayer: https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.example, PID: 11012
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=flutter_sound_channel_01 pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x48 color=0x00000000 category=transport actions=3 vis=PUBLIC)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```
Do you have an idea of what I did wrong ?
Thank you.

**Comment by Larpoux** [comment]
OK Guys and girls.
I found my bug : await was missing on calling releaseAudioPlayer().

Sorry for the noise.

**Comment by Larpoux** [comment]
I am able to run my App example on : 
- Emulator SDK 24
- Emulator SDK 26
- Emulator SDK 28
- Huawei Mediapad M5

But I still have a crash with a Xiamomi Mi Max 3 : 
```
I/flutter: startPlayer result: https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3
I/flutter: startPlayer: https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.example, PID: 24041
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=flutter_sound_channel_01 pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x48 color=0x00000000 category=transport actions=3 vis=PUBLIC)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```

**Comment by Larpoux** [comment]
@salvatore373 : 

I do not know if it is relevant, but I do not have any more the crash on Xiaomi Mi Max 3 after
checking-out your commit of Sunday.
Perhaps the commit you did yesterday is bad.

**Comment by Larpoux** [comment]
Ok, today it works. 😃
