### ISSUE TITLE
[FLAUTO] attachNewPlayer called in state 4

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#239]
### Version of flutter_sound
Flauto

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behaviour
Pause/resume/pause/resume

### Actual behaviour
crash

### Tested environment (Emulator? Real Device?)
real device Xiaomi Mi Max 3

### Steps to reproduce the behaviour
press pause/resume/pause/resume/... very quickly on ```Diglot Korean```

here are the logs : 
```
D/FlutterSoundPlugin(30063): Plays completed.
V/MediaPlayer(30063): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(30063): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(30063): stop called in state 1, mPlayer(0x0)
E/MediaPlayerNative(30063): error (-38, 0)
V/MediaPlayer(30063): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(30063): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(30063): stop called in state 0, mPlayer(0x0)
V/MediaPlayer(30063): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(30063): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(30063): stop called in state 0, mPlayer(0x0)
V/MediaPlayer(30063): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(30063): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(30063): stop called in state 0, mPlayer(0x0)
V/MediaPlayer(30063): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(30063): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(30063): attachNewPlayer called in state 4
D/AndroidRuntime(30063): Shutting down VM
E/AndroidRuntime(30063): FATAL EXCEPTION: main
E/AndroidRuntime(30063): Process: xyz.canardoux.dark_diglot, PID: 30063
E/AndroidRuntime(30063): java.lang.IllegalStateException
E/AndroidRuntime(30063): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/AndroidRuntime(30063): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1304)
E/AndroidRuntime(30063): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1287)
E/AndroidRuntime(30063): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1241)
E/AndroidRuntime(30063): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1217)
E/AndroidRuntime(30063): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1184)
E/AndroidRuntime(30063): 	at com.dooboolab.fluttersound.BackgroundAudioService$2.onPlayFromMediaId(BackgroundAudioService.java:150)
E/AndroidRuntime(30063): 	at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlayFromMediaId(MediaSessionCompat.java:1410)
E/AndroidRuntime(30063): 	at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlayFromMediaId(MediaSessionCompatApi21.java:202)
E/AndroidRuntime(30063): 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1410)
E/AndroidRuntime(30063): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(30063): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(30063): 	at android.app.ActivityThread.main(ActivityThread.java:6668)
E/AndroidRuntime(30063): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30063): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(30063): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```

**Comment by Larpoux** [comment]
Something similar, but the exception is : 
```attachNewPlayer called in state 8```

```
I/MediaPlayer(  333): [HSM] stayAwake false uid: 10666, pid: 333
E/MediaPlayerNative(  333): stop called in state 0, mPlayer(0x0)
D/MediaPlayerNative(  333): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative(  333): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
I/MediaPlayer(  333): [HSM] stayAwake false uid: 10666, pid: 333
V/MediaPlayer(  333): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(  333): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayer(  333): [HSM] stayAwake false uid: 10666, pid: 333
E/MediaPlayerNative(  333): stop called in state 0, mPlayer(0x0)
D/MediaPlayerNative(  333): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative(  333): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
I/MediaPlayer(  333): [HSM] stayAwake false uid: 10666, pid: 333
V/MediaPlayer(  333): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(  333): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayerNative(  333): setDataSource(95, 0, 576460752303423487)
I/MediaPlayerNative(  333): setDataSource(112, 0, 576460752303423487)
D/MediaPlayerNative(  333): Message: MEDIA_PREPARED(1), ext1=0, ext2=0x0
D/MediaPlayerNative(  333): [notify] : [1204] callback app listenerNotNull=1, send=1
D/MediaPlayerNative(  333): [notify] : [1216] callback application
E/MediaPlayerNative(  333): attachNewPlayer called in state 8
D/MediaPlayer(  333): setDataSource failed:
D/MediaPlayer(  333): java.lang.IllegalStateException
D/MediaPlayer(  333): 	at android.media.MediaPlayer._setDataSource(Native Method)
D/MediaPlayer(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1282)
D/MediaPlayer(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1265)
D/MediaPlayer(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1196)
D/MediaPlayer(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1169)
D/MediaPlayer(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1136)
D/MediaPlayer(  333): 	at com.dooboolab.fluttersound.BackgroundAudioService$2.onPlayFromMediaId(BackgroundAudioService.java:150)
D/MediaPlayer(  333): 	at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlayFromMediaId(MediaSessionCompat.java:1410)
D/MediaPlayer(  333): 	at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlayFromMediaId(MediaSessionCompatApi21.java:202)
D/MediaPlayer(  333): 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1362)
D/MediaPlayer(  333): 	at android.os.Handler.dispatchMessage(Handler.java:108)
D/MediaPlayer(  333): 	at android.os.Looper.loop(Looper.java:166)
D/MediaPlayer(  333): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
D/MediaPlayer(  333): 	at java.lang.reflect.Method.invoke(Native Method)
D/MediaPlayer(  333): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
D/MediaPlayer(  333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
D/AndroidRuntime(  333): Shutting down VM
E/AndroidRuntime(  333): FATAL EXCEPTION: main
E/AndroidRuntime(  333): Process: xyz.canardoux.dark_diglot, PID: 333
E/AndroidRuntime(  333): java.lang.IllegalStateException
E/AndroidRuntime(  333): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/AndroidRuntime(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1282)
E/AndroidRuntime(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1265)
E/AndroidRuntime(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1196)
E/AndroidRuntime(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1169)
E/AndroidRuntime(  333): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1136)
E/AndroidRuntime(  333): 	at com.dooboolab.fluttersound.BackgroundAudioService$2.onPlayFromMediaId(BackgroundAudioService.java:150)
E/AndroidRuntime(  333): 	at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlayFromMediaId(MediaSessionCompat.java:1410)
E/AndroidRuntime(  333): 	at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlayFromMediaId(MediaSessionCompatApi21.java:202)
E/AndroidRuntime(  333): 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1362)
E/AndroidRuntime(  333): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(  333): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(  333): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AndroidRuntime(  333): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  333): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(  333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
I/Process (  333): Sending signal. PID: 333 SIG: 9
Lost connection to device.
```

**Comment by Larpoux** [comment]
I will reopen this Problem Report if I encounter again this issue

**Comment by oussamaMaaroufi** [comment]
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
I/chatty  ( 5612): uid=10249(com.example.pharmacies) identical 1 line
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
I/chatty  ( 5612): uid=10249(com.example.pharmacies) identical 1 line
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
I/chatty  ( 5612): uid=10249(com.example.pharmacies) identical 3 lines
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
I/chatty  ( 5612): uid=10249(com.example.pharmacies) identical 1 line
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
I/chatty  ( 5612): uid=10249(com.example.pharmacies) identical 2 lines
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
W/IInputConnectionWrapper( 5612): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 5612): getTextBeforeCursor on inactive InputConnection
D/MediaPlayerNative( 5612): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
W/libEGL  ( 5612): EGLNativeWindowType 0x79b0910010 disconnect failed
