### ISSUE TITLE
[FLAUTO] Skip forward/backward on the Android lock-screen

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#241]
### Version of flutter_sound
Flauto

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
The user callbacks should be called

### Actual behavior
The user callbacks are not called.

### Tested environment (Emulator? Real Device?)
Real Xiaomi MiMax3

### Steps to reproduce the behavior
- Launch @salvatore373  's  example
- Start playing the Remote File Example
- Go to the lock screen and press "Skip forward"

Here are the logs : 
```
I/zygote64(21326): Do full code cache collection, code=124KB, data=79KB
I/zygote64(21326): After code cache collection, code=97KB, data=55KB
W/IInputConnectionWrapper(21326): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(21326): getTextBeforeCursor on inactive InputConnection
E/flutter (30318): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'markNeedsBuild' was called on null.
E/flutter (30318): Receiver: null
E/flutter (30318): Tried calling: markNeedsBuild()
E/flutter (30318): #0      State.setState (package:flutter/src/widgets/framework.dart:1253)
E/flutter (30318): #1      Automate.goAutomate (package:dark_diglot/automate.dart:147)
E/flutter (30318): <asynchronous suspension>
E/flutter (30318): #2      Automate.runAutomate (package:dark_diglot/automate.dart:172)
E/flutter (30318): <asynchronous suspension>
E/flutter (30318): #3      Practice.playCard (package:dark_diglot/practice.dart:181)
E/flutter (30318): <asynchronous suspension>
E/flutter (30318): #4      PracticeView.showCard (package:dark_diglot/practice_form.dart:120)
E/flutter (30318): <asynchronous suspension>
E/flutter (30318): #5      browseCard (package:dark_diglot/practice.dart:68)
E/flutter (30318): <asynchronous suspension>
E/flutter (30318): 
```

@salvatore373 : this must be fixed before releasing Flauto.

**Comment by Larpoux** [comment]
This bug does not occur with my ```flauto``` branch.
So it's OK for me and I can close this issue.
