### ISSUE TITLE
player crashes the app on Android

### ISSUE THREAD

**Issue by villesau** [dooboolab/flutter_sound#27]
### Version of flutter_sound
`1.2.1`
## flutter doctor
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.11.13, on Mac OS X 10.14.2 18C54, locale en-FI)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[!] Android Studio (not installed)
[!] VS Code (version 1.30.1)
[✓] Connected device (1 available)

```
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
player should not crash
### Actual behavior
player crashes, which crashes the whole app
### Tested environment (Emulator? Real Device?)
real device, Samsung Galaxy S9
### Steps to reproduce the behavior
let the audio play until end, it does not happen cosistently
### Exception:

```
V/MediaPlayer-JNI( 1705): stop
V/MediaPlayerNative( 1705): stop
V/MediaPlayerNative( 1705): message received msg=8, ext1=0, ext2=0
V/MediaPlayerNative( 1705): unrecognized message: (8, 0, 0)
V/MediaPlayerNative( 1705): callback application
V/MediaPlayerNative( 1705): back from callback
V/MediaPlayer( 1705): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 1705): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer-JNI( 1705): release
V/MediaPlayerNative( 1705): setListener
V/MediaPlayerNative( 1705): disconnect
V/MediaPlayer-JNI( 1705): getDuration: 2400 (msec)
E/AndroidRuntime( 1705): FATAL EXCEPTION: Timer-2
E/AndroidRuntime( 1705): Process: com.lacorder.lacorder, PID: 1705
E/AndroidRuntime( 1705): java.lang.IllegalStateException
E/AndroidRuntime( 1705): 	at android.media.MediaPlayer.getCurrentPosition(Native Method)
E/AndroidRuntime( 1705): 	at com.dooboolab.fluttersound.FlutterSoundPlugin$2$1.run(FlutterSoundPlugin.java:232)
E/AndroidRuntime( 1705): 	at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime( 1705): 	at java.util.TimerThread.run(Timer.java:505)
V/MediaPlayerNative( 1705): destructor
V/MediaPlayerNative( 1705): disconnect
W/MediaPlayer( 1705): mediaplayer went away with unhandled events
```

**Comment by donpeter06** [comment]
I have the same issue, I use getCurrentPosition and getDuration to determine when the player is done. but as the player reaches end of file, app crashes.

**Comment by donpeter06** [comment]
I got the issue fixed for me.
@villesau may I have the code snippet where you have defined the 
`.onPlayerStateChanged.listen((e)){
}`

**Comment by gerry05** [comment]
@donpeter06  how did you solved this issue?
