### ISSUE TITLE
[BUG] Android: Can't record AMR_WB

### ISSUE THREAD

**Issue by tgarm** [dooboolab/flutter_sound#380]
## Flutter Sound Version : 

- It happens on:
`  flutter_sound_lite: ^5.0.1`

----------------------------------------------------------

## Severity

- Exception thrown:
 When try to record in AMR_WB:
`      await _recorder.startRecorder(codec: Codec.amrWB, sampleRate: 16000,
          toFile: _apath, audioSource: AudioSource.microphone);`

Exception thrown:

```
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): Failed to handle method call
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): java.lang.ArrayIndexOutOfBoundsException: length=13; index=13
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at com.dooboolab.fluttersound.FlutterSoundRecorder.isEncoderSupported(FlutterSoundRecorder.java:266)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at com.dooboolab.fluttersound.FlautoRecorderPlugin.onMethodCall(FlutterSoundRecorder.java:102)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at android.os.Looper.loop(Looper.java:170)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at android.app.ActivityThread.main(ActivityThread.java:7069)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(26687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841)
Lost connection to device.
```
--------------------------------------------------------

## Platform

- Android 

----------------------------------------------

## Analyze

I checked the Android code at _FlutterSoundRecorder.java_ , and found the array lack the corresponding item for AMR_WB:

I'm trying to resolve it and make a PR.

**Comment by Larpoux** [comment]
@tgarm , Hi,

Yes,I realized some days ago that I forgot those new codecs in some tables.
I am sorry. 👎 
I fixed that in my branch, but unfortunately my branch (5.1.0) is actually not ready to be published.

A PR is welcome.
