### ISSUE TITLE
[BUG] App Crashes

### ISSUE THREAD

**Issue by kmusham** [dooboolab/flutter_sound#435]
## Flutter Sound Version : 
3.1.10

- **Released** or **Beta** version ?

- Version number ?
3.1.10

- **FULL** or **LITE** flavor ?

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

----------------------------------------------------------

## Severity

- Crash ?
Yes

- Result is not what expected ?

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ?
Yes
- Both ?

- Emulator ? 
Yes
- Real device ?
Yes
----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

2020-08-19 13:00:03.061 30099-30099/<app id> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <app id>, PID: 30099
    java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4204)
        at android.app.ActivityThread.access$1500(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.dooboolab.fluttersound.BackgroundAudioService.initMediaSession(BackgroundAudioService.java:565)
        at com.dooboolab.fluttersound.BackgroundAudioService.onCreate(BackgroundAudioService.java:474)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4192)
        at android.app.ActivityThread.access$1500(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2020-08-19 13:00:04.544 30099-30116/<app id> W/MediaPlayer-JNI: MediaPlayer finalized without being released

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

**To Reproduce**
1. Install the App 
2) Turn on Airplane mode
3) Turn off Airplane mode
4) App crashes with above stack trace

**Expected behavior**

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
This issue has been fixed in 4.0.3
We do not support version 3 any more.

Please re-open this issue if this answer does not satisfy you
