### ISSUE TITLE
[HELP] startPlayerFromTrack throws exception after openAudioSession, but works with openAudioSessionWithUI

### ISSUE THREAD

**Issue by petroniuchacz** [dooboolab/flutter_sound#445]
I need Help for :

- Using the API ?

-------------------------------------
## Here is my question :
Android 8 and 10.
I'm getting an exception when calling startPlayerFromTrack after openAudioSession, but the same code works if I do openAudioSessionWithUI. Am I doing something wrong or is it a bug?
```dart
  final _player = FlutterSoundPlayer();
  await _player.openAudioSession(
      focus: AudioFocus.requestFocusAndKeepOthers,
      category: SessionCategory.playback,
      mode: SessionMode.modeSpokenAudio,
      device: AudioDevice.speaker,
      audioFlags: outputToSpeaker | allowBlueTooth | allowHeadset,
    );

  final track = Track(trackPath: newPath, codec: Codec.aacADTS);
  await _player.startPlayerFromTrack(
      track,
      whenFinished: () => _whenFinished(whenFinished),
  );
```

throws 

```
I/flutter (26589): FS:---> openAudioSession 
E/BluetoothAdapter(26589): Bluetooth binder is null
I/flutter (26589): FS:<--- openAudioSession 
I/flutter (26589): FS:---> setSubscriptionDuration 
I/flutter (26589): FS:---> startPlayerFromTrack 
I/flutter (26589): Audio session is not open
E/flutter (26589): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Instance of '_notOpen'
E/flutter (26589): #0      FlutterSoundPlayer.startPlayerFromTrack (package:flutter_sound/src/flutter_sound_player.dart:666:7)
E/flutter (26589): #1      AudioPlayerService._startPlaybackOtherTrack (package:siftmobile/service/media/audio_player_service/audio_player_service.dart:98:19)
E/flutter (26589): #2      AudioPlayerService.play (package:siftmobile/service/media/audio_player_service/audio_player_service.dart:61:21)
E/flutter (26589): #3      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (26589): #4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (26589): #5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (26589): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (26589): #7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (26589): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
E/flutter (26589): #9      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (26589): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (26589): #11     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (26589): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (26589): #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (26589): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

Result of the same code, but using openAudioSessionWithUI:

```
I/flutter (26589): FS:---> openAudioSessionWithUI 
E/BluetoothAdapter(26589): Bluetooth binder is null
I/flutter (26589): FS:<--- openAudioSessionWithUI 
I/flutter (26589): FS:---> setSubscriptionDuration 
I/flutter (26589): FS:---> startPlayerFromTrack 
I/flutter (26589): FS:---> stop 
E/MediaPlayerNative(26589): stop called in state 1, mPlayer(0x0)
E/MediaPlayerNative(26589): error (-38, 0)
V/MediaPlayer(26589): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(26589): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter (26589): FS:<---- setSubscriptionDuration 
I/flutter (26589): FS:<--- stop 
I/flutter (26589): FS:---> _convert 
I/flutter (26589): FS:---> needToConvert 
I/flutter (26589): FS:<--- needToConvert 
I/flutter (26589): FS:<--- _convert 
E/MediaPlayerNative(26589): stop called in state 0, mPlayer(0x0)
V/MediaPlayer(26589): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(26589): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter (26589): FS:---> channelMethodCallHandler : updatePlaybackState
I/flutter (26589): FS:---> updatePlaybackState 
I/flutter (26589): FS:<--- updatePlaybackState 
I/flutter (26589): FS:<--- channelMethodCallHandler : updatePlaybackState
V/MediaPlayer(26589): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(26589): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService(26589): MediaHTTPService(android.media.MediaHTTPService@ac98e39): Cookies: null
I/flutter (26589): FS:<--- startPlayerFromTrack 
I/flutter (26589): FS:---> channelMethodCallHandler : updatePlaybackState
I/flutter (26589): FS:---> updatePlaybackState 
I/flutter (26589): FS:<--- updatePlaybackState 
I/flutter (26589): FS:<--- channelMethodCallHandler : updatePlaybackState
V/MediaHTTPService(26589): makeHTTPConnection: CookieHandler (java.net.CookieManager@4f3f1e5) exists.
V/MediaHTTPService(26589): makeHTTPConnection(android.media.MediaHTTPService@ac98e39): cookieHandler: java.net.CookieManager@4f3f1e5 Cookies: null
I/flutter (26589): FS:---> channelMethodCallHandler : updatePlaybackState
I/flutter (26589): FS:---> updatePlaybackState 
I/flutter (26589): FS:<--- updatePlaybackState 
I/flutter (26589): FS:<--- channelMethodCallHandler : updatePlaybackState
I/flutter (26589): FS:---> seekToPlayer 
I/flutter (26589): FS:<--- seekToPlayer 
I/flutter (26589): FS:---> channelMethodCallHandler : updatePlaybackState
I/flutter (26589): FS:---> updatePlaybackState 
I/flutter (26589): FS:<--- updatePlaybackState 
I/flutter (26589): FS:<--- channelMethodCallHandler : updatePlaybackState
```

**Comment by Larpoux** [comment]
To play tracks, **you must** open your session with `openAudioSessionWithUI()`.
This is why you have an exception when you use `openAudioSession()`.

When you use `openAudioSessionWithUI()`, actually you do not have any exception.

Verify your parameters.
It seems that you provided a Remote source (HTTP).
Verify that this source is correct.
Try also to remove the `seekToPlayer()` call.

Be aware that fetching a remote audio file can be time long if the file is not cached.

**Comment by petroniuchacz** [comment]
With startPlayer() it works. Thx!
