### ISSUE TITLE
output file has already been set error

### ISSUE THREAD

**Issue by ened** [dooboolab/flutter_sound#53]
### Version of flutter_sound

1.3.3

## flutter doctor

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.3.2, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.2 at /Users/ened/dev/flutter
    • Framework revision 046f960ae2 (3 days ago), 2019-02-28 23:05:45 -0800
    • Engine revision 99f3f7a9c2
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Pixel 2 • HT83G1A03545 • android-arm64 • Android 9 (API 28)
```

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Recording should start/stop smoothly and discard any recordings which are not used.
The plugin should handle such stress testing gracefully & make sure Android APIs are opened/closed on time.

### Actual behavior

Quickly starting & stopping will cause the stack trace below.

### Tested environment (Emulator? Real Device?)

Pixel XL 2

### Steps to reproduce the behavior

*Quickly* start & stop the audio recording will yield a error like this:

```
E/FlutterSoundPlugin(19490): Exception: 
E/FlutterSoundPlugin(19490): java.lang.IllegalStateException
E/FlutterSoundPlugin(19490): 	at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin(19490): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:961)
E/FlutterSoundPlugin(19490): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:155)
E/FlutterSoundPlugin(19490): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.onMethodCall(FlutterSoundPlugin.java:66)
E/FlutterSoundPlugin(19490): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/FlutterSoundPlugin(19490): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/FlutterSoundPlugin(19490): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/FlutterSoundPlugin(19490): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterSoundPlugin(19490): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/FlutterSoundPlugin(19490): 	at android.os.Looper.loop(Looper.java:160)
E/FlutterSoundPlugin(19490): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/FlutterSoundPlugin(19490): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterSoundPlugin(19490): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/FlutterSoundPlugin(19490): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Once this happens, the App needs to be restarted as the Plugin is not released/recreating a faulty MediaRecorder instance (perhaps another bug).

My suggestion is to introduce a single threaded command scheduler inside the plugin, which runs everything in a sequence.

For example:
```
Schedulers.from(Executors.newSingleThreadExecutor())
```

Then, this scheduler can be fed `Runnable`s which run the actual plugin code.

**Comment by hyochan** [comment]
@ened Thank you for nice `issue` with the template. Could you help us with this when you have time?

**Comment by ened** [comment]
@hyochan yes, will do.
